--  Rename the column ST_ID to STUDENT_ID in the STUDENTS table
ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;

SELECT * FROM STUDENTS;

-- Change the data type of columns ST_NAME and ST_LAST to VARCHAR(30)
ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(30);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(30);

-- Rename the column INTEREST to INTERESTS in the INTERESTS table
ALTER TABLE INTERESTS RENAME COLUMN INTEREST TO INTERESTS;

-- Create a backup table INTERESTS_BACKUP to store interests as an array of strings for each student
CREATE TABLE INTERESTS_BACKUP (
    STUDENT_ID INTEGER REFERENCES STUDENTS(STUDENT_ID),
    INTERESTS VARCHAR[]
);
-- Insert data into the INTERESTS_BACKUP table
INSERT INTO INTERESTS_BACKUP (STUDENT_ID, INTERESTS)
SELECT STUDENT_ID, ARRAY_AGG(INTERESTS) 
FROM INTERESTS 
GROUP BY STUDENT_ID;

-- Drop the original INTERESTS table
DROP TABLE INTERESTS;

-- Rename the INTERESTS_BACKUP table to INTERESTS to replace the original table
ALTER TABLE INTERESTS_BACKUP RENAME TO INTERESTS

SELECT * FROM INTERESTS;
